[package]
name = "hist_inverter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../db" }
structopt = { version = "0.3", default-features = false }
error-chain = { version = "0.12.4"}